name: CI/CD using GitHub Actions & Docker

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.YML }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Make application-prod.yml
        run: |
          echo "${{ secrets.YML_PROD }}" > ./src/main/resources/application-prod.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set lowercase Docker username
        id: set_lowercase_docker_username
        run: echo "LOWERCASE_DOCKER_USERNAME=$(echo '${{ secrets.DOCKER_USERNAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Docker build & push to prod
        run: |
          docker build -f Dockerfile -t ${{ env.LOWERCASE_DOCKER_USERNAME }}/docker-test-prod:latest .
          docker push ${{ env.LOWERCASE_DOCKER_USERNAME }}/docker-test-prod:latest

      - name: Deploy to prod
        uses: appleboy/ssh-action@v1.0.3
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            whoami
            sudo docker ps
            sudo docker pull ${{ env.LOWERCASE_DOCKER_USERNAME }}/docker-test-prod:latest
            sudo docker run -d -p 8080:8080 ${{ env.LOWERCASE_DOCKER_USERNAME }}/docker-test-prod:latest
            sudo docker image prune -f
